title: GBICi5-Python-1-Colourful-Creations
hero_image: images/banner.png
description: GBICi5-Python-1-Colourful-Creations description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-21"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
